{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE ViewPatterns #-}
{-# LANGUAGE RecordWildCards #-}

import AnswerTypes
import Data.Char
import Data.List
import Data.Function

data Result = Result
              {rNumber :: Int -- problem number
              ,rPolarity :: Bool -- False if the negation of the conclusion is proven.
              ,rProven :: Bool -- True if Qed, False if abort.
              }
              deriving Show

parseWords :: Maybe (Int,Bool) -> [String] -> [Result]
parseWords c@(Just(rNumber,rPolarity)) ("Qed.":ws) = Result{rProven = True, ..}:parseWords c ws
parseWords c@(Just(rNumber,rPolarity)) ("Abort":ws) = Result{rProven = False, ..}:parseWords c ws
parseWords _ ("Theorem":_thmName:('P':'r':'o':'b':'l':'e':'m':pbInfo):ws) = parseWords (Just (rNumber,rPolarity)) ws
  where (read -> rNumber,_variant:(read . takeWhile isAlpha -> rPolarity)) = span isDigit pbInfo
parseWords c (_:ws) = parseWords c ws
parseWords _ [] = []

(-->) :: Bool -> Bool -> Bool
False --> _ = True
_ --> True = True
True --> False = False

evalPb :: [Result] -> (Int,Answer)
evalPb rs@(Result{rNumber=n}:_)
  | and [rProven --> rPolarity | Result{..} <- rs] = (n,Yes)
  | and [rProven --> not rPolarity | Result{..} <- rs] = (n,No)
  | and [not rProven | Result{..} <- rs] = (n,Unknown)
  | otherwise = (n,Unclear (show rs))


eval :: [Result] -> [(Int,Answer)]
eval = map evalPb . groupBy ((==) `on` rNumber) . sortBy (compare `on` rNumber) 

---------------------------------------------------------------
-- turn the coq proofs (or lack thereof) into entailment values.

main :: IO ()
main = do
  ws <- (concatMap words . lines) <$> readFile "Proofs.v"
  let proofs = eval $ parseWords Nothing ws 
  mapM_ print [(n,a,lookup n proofs) | (n,a) <- answers]

-- >>> main
-- (1,Yes,Nothing)
-- (2,Yes,Nothing)
-- (3,Yes,Nothing)
-- (4,Yes,Nothing)
-- (5,Yes,Nothing)
-- (6,No,Nothing)
-- (7,Yes,Nothing)
-- (8,Yes,Nothing)
-- (9,Yes,Nothing)
-- (10,Yes,Nothing)
-- (11,Yes,Nothing)
-- (12,Unclear "Not many",Nothing)
-- (13,Yes,Nothing)
-- (14,No,Nothing)
-- (15,Yes,Nothing)
-- (16,Unclear "At most two",Nothing)
-- (17,Yes,Nothing)
-- (18,Yes,Nothing)
-- (19,Yes,Nothing)
-- (20,Yes,Nothing)
-- (21,Yes,Nothing)
-- (22,Unknown,Nothing)
-- (23,Yes,Nothing)
-- (24,Yes,Nothing)
-- (25,Yes,Nothing)
-- (26,Yes,Nothing)
-- (27,Yes,Nothing)
-- (28,Unknown,Nothing)
-- (29,Yes,Nothing)
-- (30,Unknown,Nothing)
-- (31,Yes,Nothing)
-- (32,Unknown,Nothing)
-- (33,Unknown,Nothing)
-- (34,Unknown,Nothing)
-- (35,Unknown,Nothing)
-- (36,Unknown,Nothing)
-- (37,Unknown,Nothing)
-- (38,No,Nothing)
-- (39,Unknown,Nothing)
-- (40,Unknown,Nothing)
-- (41,Unknown,Nothing)
-- (42,Unknown,Nothing)
-- (43,Unknown,Nothing)
-- (44,Yes,Nothing)
-- (45,Unknown,Nothing)
-- (46,No,Nothing)
-- (47,Unknown,Nothing)
-- (48,Yes,Nothing)
-- (49,Yes,Nothing)
-- (50,Unknown,Nothing)
-- (51,Unknown,Nothing)
-- (52,Unknown,Nothing)
-- (53,Unknown,Nothing)
-- (54,Unknown,Nothing)
-- (55,Yes,Nothing)
-- (56,Unknown,Nothing)
-- (57,Yes,Nothing)
-- (58,Unknown,Nothing)
-- (59,Yes,Nothing)
-- (60,Unknown,Nothing)
-- (61,Unclear "Yes, if both commissioners are female; otherwise there are more than two commissioners.",Nothing)
-- (62,Unclear "No, if both commissioners are female; otherwise there are more than two commissioners.",Nothing)
-- (63,Yes,Nothing)
-- (64,Unknown,Nothing)
-- (65,Unknown,Nothing)
-- (66,Yes,Nothing)
-- (67,Yes,Nothing)
-- (68,Yes,Nothing)
-- (69,Yes,Nothing)
-- (70,No,Nothing)
-- (71,Unknown,Nothing)
-- (72,Unknown,Nothing)
-- (73,Unknown,Nothing)
-- (74,Unknown,Nothing)
-- (75,Unknown,Nothing)
-- (76,Yes,Nothing)
-- (77,Unclear "Yes, if both commissioners are female; otherwise there are more than two commissioners.",Nothing)
-- (78,Unclear "No, if both commissioners are female; otherwise there are more than two commissioners.",Nothing)
-- (79,Unknown,Nothing)
-- (80,Yes,Nothing)
-- (81,Yes,Nothing)
-- (82,Yes,Nothing)
-- (83,Unknown,Nothing)
-- (84,Yes,Nothing)
-- (85,No,Nothing)
-- (86,No,Nothing)
-- (87,Unclear "Yes, on one reading",Nothing)
-- (88,Unclear "Don't know, on one reading",Nothing)
-- (89,Yes,Nothing)
-- (90,Yes,Nothing)
-- (91,Unknown,Nothing)
-- (92,Yes,Nothing)
-- (93,Yes,Nothing)
-- (94,Unknown,Nothing)
-- (95,Unknown,Nothing)
-- (96,Yes,Nothing)
-- (97,Yes,Nothing)
-- (98,Unknown,Nothing)
-- (99,Yes,Nothing)
-- (100,Yes,Nothing)
-- (101,Yes,Nothing)
-- (102,Unknown,Nothing)
-- (103,Yes,Nothing)
-- (104,Unknown,Nothing)
-- (105,No,Nothing)
-- (106,No,Nothing)
-- (107,Yes,Nothing)
-- (108,Yes,Nothing)
-- (109,Unclear "No, just one",Nothing)
-- (110,Yes,Nothing)
-- (111,Unclear "Yes, on a collective/cumulative reading of the conclusion.",Nothing)
-- (112,Unclear "Yes, on a distributive reading of \"Smith and Jones\".",Nothing)
-- (113,Yes,Nothing)
-- (114,Yes,Just Yes)
-- (115,Yes,Just Yes)
-- (116,Yes,Just Yes)
-- (117,Yes,Just Yes)
-- (118,Yes,Nothing)
-- (119,No,Nothing)
-- (120,Yes,Nothing)
-- (121,Yes,Nothing)
-- (122,Yes,Nothing)
-- (123,Yes,Just Yes)
-- (124,Yes,Just Yes)
-- (125,Unknown,Just Yes)
-- (126,Yes,Just Yes)
-- (127,Unclear "Yes, on a distributive reading of the question.",Just Yes)
-- (128,Yes,Just Yes)
-- (129,Unclear "Yes, on one possible reading",Just Yes)
-- (130,Unclear "Don't know, on one possible reading",Just Yes)
-- (131,Yes,Just Yes)
-- (132,Yes,Just Yes)
-- (133,Yes,Just Yes)
-- (134,Yes,Just Yes)
-- (135,Yes,Just Yes)
-- (136,Unknown,Just Yes)
-- (137,Yes,Nothing)
-- (138,Yes,Just Yes)
-- (139,Yes,Just Yes)
-- (140,Yes,Just Yes)
-- (141,Unknown,Just Yes)
-- (142,Yes,Just Yes)
-- (143,Unknown,Just Yes)
-- (144,Yes,Just Yes)
-- (145,Yes,Just Yes)
-- (146,Yes,Just Yes)
-- (147,No,Just No)
-- (148,Yes,Just Yes)
-- (149,Yes,Just Yes)
-- (150,Yes,Just Yes)
-- (151,Yes,Just Yes)
-- (152,Yes,Just Yes)
-- (153,Yes,Just Yes)
-- (154,Yes,Just Yes)
-- (155,Yes,Just Yes)
-- (156,Unknown,Nothing)
-- (157,Yes,Just Yes)
-- (158,Unknown,Just Yes)
-- (159,Yes,Just Yes)
-- (160,Unclear "Yes, on one possible reading",Just Yes)
-- (161,Unclear "Don't know, on one possible reading",Just Yes)
-- (162,Yes,Just Yes)
-- (163,No,Nothing)
-- (164,Yes,Nothing)
-- (165,Yes,Nothing)
-- (166,Yes,Nothing)
-- (167,No,Nothing)
-- (168,Yes,Nothing)
-- (169,Unclear "Yes, on one possible reading",Nothing)
-- (170,Unclear "Yes, on one possible reading",Nothing)
-- (171,Yes,Nothing)
-- (172,Yes,Nothing)
-- (173,Yes,Nothing)
-- (174,Unknown,Nothing)
-- (175,Unclear "Yes, on one possible reading/parse",Nothing)
-- (176,Unclear "Yes, on one possible reading/parse",Nothing)
-- (177,Unknown,Nothing)
-- (178,Yes,Nothing)
-- (179,Yes,Nothing)
-- (180,Yes,Nothing)
-- (181,Unknown,Nothing)
-- (182,Unclear "Yes, on one reading",Nothing)
-- (183,Unclear "Yes, on one reading",Nothing)
-- (184,Unknown,Nothing)
-- (185,Unclear "Yes, on one reading",Nothing)
-- (186,Unclear "Yes, on one reading",Nothing)
-- (187,Unclear "Yes, on one reading",Nothing)
-- (188,Unknown,Nothing)
-- (189,Unclear "Yes, on one reading",Nothing)
-- (190,Unclear "Yes, on one reading",Nothing)
-- (191,Yes,Nothing)
-- (192,Unknown,Nothing)
-- (193,Yes,Nothing)
-- (194,Unknown,Nothing)
-- (195,Yes,Nothing)
-- (196,Yes,Nothing)
-- (197,Yes,Nothing)
-- (198,Unclear "No / don't know",Nothing)
-- (199,Unclear "Yes (for a former university student)",Nothing)
-- (200,Unknown,Nothing)
-- (201,Unknown,Nothing)
-- (202,Yes,Nothing)
-- (203,Yes,Nothing)
-- (204,No,Nothing)
-- (205,No,Nothing)
-- (206,Unknown,Nothing)
-- (207,Unknown,Nothing)
-- (208,Yes,Nothing)
-- (209,No,Nothing)
-- (210,No,Nothing)
-- (211,No,Nothing)
-- (212,Yes,Nothing)
-- (213,Unclear "??: Yes for a mouse; ?? No for an animal",Nothing)
-- (214,Yes,Nothing)
-- (215,Unknown,Nothing)
-- (216,Yes,Nothing)
-- (217,Unknown,Nothing)
-- (218,Yes,Nothing)
-- (219,Unknown,Nothing)
-- (220,Yes,Nothing)
-- (221,Unknown,Nothing)
-- (222,Unknown,Nothing)
-- (223,No,Nothing)
-- (224,Yes,Nothing)
-- (225,Unknown,Nothing)
-- (226,Unknown,Nothing)
-- (227,No,Nothing)
-- (228,Unknown,Nothing)
-- (229,No,Nothing)
-- (230,Yes,Nothing)
-- (231,Unknown,Nothing)
-- (232,Yes,Nothing)
-- (233,Yes,Nothing)
-- (234,Unknown,Nothing)
-- (235,Yes,Nothing)
-- (236,Yes,Nothing)
-- (237,Yes,Nothing)
-- (238,Yes,Nothing)
-- (239,Yes,Nothing)
-- (240,Unknown,Nothing)
-- (241,Yes,Nothing)
-- (242,Yes,Nothing)
-- (243,Yes,Nothing)
-- (244,Unclear "Yes, on one reading of the premise",Nothing)
-- (245,Unclear "Yes, on one reading of the premise",Nothing)
-- (246,Yes,Nothing)
-- (247,Unknown,Nothing)
-- (248,Yes,Nothing)
-- (249,Yes,Nothing)
-- (250,Unclear "Yes, on one reading of the premise",Nothing)
-- (251,Yes,Nothing)
-- (252,Yes,Nothing)
-- (253,Unknown,Nothing)
-- (254,Unknown,Nothing)
-- (255,Yes,Nothing)
-- (256,Unclear "Don't know, on one reading of the premise",Nothing)
-- (257,Unclear "Yes, on one reading of the premise",Nothing)
-- (258,No,Nothing)
-- (259,Yes,Nothing)
-- (260,Yes,Nothing)
-- (261,Yes,Nothing)
-- (262,Yes,Nothing)
-- (263,Unknown,Nothing)
-- (264,Yes,Nothing)
-- (265,Yes,Nothing)
-- (266,Yes,Nothing)
-- (267,Yes,Nothing)
-- (268,Yes,Nothing)
-- (269,Unknown,Nothing)
-- (270,Yes,Nothing)
-- (271,Unknown,Nothing)
-- (272,Unknown,Nothing)
-- (273,Unknown,Nothing)
-- (274,Unknown,Nothing)
-- (275,Unknown,Nothing)
-- (276,Unclear "",Nothing)
-- (277,Unknown,Nothing)
-- (278,No,Nothing)
-- (279,No,Nothing)
-- (280,Unknown,Nothing)
-- (281,Unknown,Nothing)
-- (282,No,Nothing)
-- (283,Unknown,Nothing)
-- (284,Yes,Nothing)
-- (285,Unknown,Nothing)
-- (286,No,Nothing)
-- (287,Unknown,Nothing)
-- (288,Yes,Nothing)
-- (289,No,Nothing)
-- (290,Yes,Nothing)
-- (291,Unclear "?Yes",Nothing)
-- (292,Unknown,Nothing)
-- (293,Unknown,Nothing)
-- (294,Yes,Nothing)
-- (295,Unknown,Nothing)
-- (296,Unknown,Nothing)
-- (297,Yes,Nothing)
-- (298,Yes,Nothing)
-- (299,No,Nothing)
-- (300,Yes,Nothing)
-- (301,Yes,Nothing)
-- (302,Yes,Nothing)
-- (303,Yes,Nothing)
-- (304,Unknown,Nothing)
-- (305,Unclear "",Nothing)
-- (306,Yes,Nothing)
-- (307,Yes,Nothing)
-- (308,Unclear "Yes on one scoping; unknown on another scoping",Nothing)
-- (309,Unclear "",Nothing)
-- (310,Unclear "",Nothing)
-- (311,Yes,Nothing)
-- (312,Yes,Nothing)
-- (313,No,Nothing)
-- (314,Yes,Nothing)
-- (315,Yes,Nothing)
-- (316,Yes,Nothing)
-- (317,Yes,Nothing)
-- (318,No,Nothing)
-- (319,Yes,Nothing)
-- (320,Yes,Nothing)
-- (321,Yes,Nothing)
-- (322,Yes,Nothing)
-- (323,Yes,Nothing)
-- (324,Yes,Nothing)
-- (325,Yes,Nothing)
-- (326,Yes,Nothing)
-- (327,Unknown,Nothing)
-- (328,Yes,Nothing)
-- (329,Unknown,Nothing)
-- (330,Yes,Nothing)
-- (331,Yes,Nothing)
-- (332,Yes,Nothing)
-- (333,Yes,Nothing)
-- (334,Yes,Nothing)
-- (335,Unknown,Nothing)
-- (336,Yes,Nothing)
-- (337,Unknown,Nothing)
-- (338,Yes,Nothing)
-- (339,No,Nothing)
-- (340,Unknown,Nothing)
-- (341,Unknown,Nothing)
-- (342,Yes,Nothing)
-- (343,Yes,Nothing)
-- (344,Yes,Nothing)
-- (345,Yes,Nothing)
-- (346,Yes,Nothing)
