{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE ViewPatterns #-}
{-# LANGUAGE RecordWildCards #-}

import AnswerTypes
import Data.Char
import Data.List
import Data.Function
import Data.Maybe
import System.Environment

data Result = Result
              {rNumber :: Int -- problem number
              ,rPolarity :: Bool -- False if the negation of the conclusion is proven.
              ,rProven :: Bool -- True if Qed, False if abort.
              }
              deriving Show

parseWords :: Maybe (Int,Bool) -> [String] -> [Result]
parseWords c@(Just(rNumber,rPolarity)) ("Qed.":ws) = Result{rProven = True, ..}:parseWords c ws
parseWords c@(Just(rNumber,rPolarity)) ("Abort":ws) = Result{rProven = False, ..}:parseWords c ws
parseWords _ ({-"Theorem":_thmName:-}('P':'r':'o':'b':'l':'e':'m':pbInfo):ws) = parseWords (Just (rNumber,rPolarity)) ws
  where (read -> rNumber,_variant:(read . takeWhile isAlpha -> rPolarity)) = span isDigit pbInfo
parseWords c (_:ws) = parseWords c ws
parseWords _ [] = []

(-->) :: Bool -> Bool -> Bool
False --> _ = True
_ --> True = True
True --> False = False

evalPb :: [Result] -> (Int,Answer)
evalPb rs@(Result{rNumber=n}:_)
  -- nothing is proven
  | and [not rProven | Result{..} <- rs] = (n,Unknown)
  -- at least one proven
  | and [rProven --> rPolarity | Result{..} <- rs] = (n,Yes)
  | and [rProven --> not rPolarity | Result{..} <- rs] = (n,No)
  | otherwise = (n,Unclear (show rs))


eval :: [Result] -> [(Int,Answer)]
eval = map evalPb . groupBy ((==) `on` rNumber) . sortBy (compare `on` rNumber) 

---------------------------------------------------------------
-- turn the coq proofs (or lack thereof) into entailment values.

compatible :: Answer -> Maybe Answer -> Bool
compatible _ Nothing = False
compatible Undef _ = True
compatible (Unclear _) _ = error "Unclear!"
compatible x (Just y) = x == y

countOk :: [(Bool,a)] -> Int
countOk = length . filter fst

count :: Show a => [(Bool,a)] -> [Char]
count xs = show (countOk xs)++"/"++show (length xs) ++ "   " ++ show (map snd $ filter (not . fst) xs)

sectionStarts :: [Int]
sectionStarts = [1,81,114,142,197,220,251,326,334,347]

showScores :: [(Int, Bool, t, Maybe a)] -> (Int,Int,Int) -> IO ()
showScores consolidated (sectionNumber,start,stop) = do
  putStrLn (" ------ Section " ++ show sectionNumber)
  putStrLn ("complete: "++count complete)
  putStrLn ("correct: "++ count correct)
  putStrLn ("score: " ++ show ((fromIntegral (countOk correct) :: Double) / (fromIntegral (length complete))))
  where inRange x = x >= start && x < stop
        correct = [(ok,n) | (n,ok,_,Just _) <- consolidated, inRange n]
        complete = [(isJust a,n) | (n,_ok,_,a) <- consolidated, inRange n]

isClear :: Answer -> Bool
isClear (Unclear _) = False
isClear _ = True

doIt :: [String] -> IO ()
doIt args = do
  files <- mapM readFile args
  let ws = (concatMap words . concat . map lines) files
  let proofs = eval $ parseWords Nothing ws
      consolidated = [(n,compatible a proof,a,proof) | (n,a) <- answers, isClear a, let proof = lookup n proofs]
  mapM_ print (parseWords Nothing ws)
  mapM_ print consolidated
  mapM_ (showScores consolidated) (zip3 [1..] sectionStarts (tail sectionStarts))
  (showScores consolidated) (0,0,220)

main :: IO ()
main = do
  args <- getArgs
  doIt args



-- >>> main
-- incomplete: 75/83
-- correct: 70/75
-- (119,True,Unknown,Just Unknown)
-- (1,False,Yes,Nothing)
-- (2,False,Yes,Nothing)
-- (3,False,Yes,Nothing)
-- (4,False,Yes,Nothing)
-- (5,False,Yes,Nothing)
-- (6,False,No,Nothing)
-- (7,False,Yes,Nothing)
-- (8,False,Yes,Nothing)
-- (9,False,Yes,Nothing)
-- (10,False,Yes,Nothing)
-- (11,False,Yes,Nothing)
-- (12,False,Unclear "Not many",Nothing)
-- (13,False,Yes,Nothing)
-- (14,False,No,Nothing)
-- (15,False,Yes,Nothing)
-- (16,False,Unclear "At most two",Nothing)
-- (17,False,Yes,Nothing)
-- (18,False,Yes,Nothing)
-- (19,False,Yes,Nothing)
-- (20,False,Yes,Nothing)
-- (21,False,Yes,Nothing)
-- (22,False,Unknown,Nothing)
-- (23,False,Yes,Nothing)
-- (24,False,Yes,Nothing)
-- (25,False,Yes,Nothing)
-- (26,False,Yes,Nothing)
-- (27,False,Yes,Nothing)
-- (28,False,Unknown,Nothing)
-- (29,False,Yes,Nothing)
-- (30,False,Unknown,Nothing)
-- (31,False,Yes,Nothing)
-- (32,False,Unknown,Nothing)
-- (33,False,Unknown,Nothing)
-- (34,False,Unknown,Nothing)
-- (35,False,Unknown,Nothing)
-- (36,False,Unknown,Nothing)
-- (37,False,Unknown,Nothing)
-- (38,False,No,Nothing)
-- (39,False,Unknown,Nothing)
-- (40,False,Unknown,Nothing)
-- (41,False,Unknown,Nothing)
-- (42,False,Unknown,Nothing)
-- (43,False,Unknown,Nothing)
-- (44,False,Yes,Nothing)
-- (45,False,Unknown,Nothing)
-- (46,False,No,Nothing)
-- (47,False,Unknown,Nothing)
-- (48,False,Yes,Nothing)
-- (49,False,Yes,Nothing)
-- (50,False,Unknown,Nothing)
-- (51,False,Unknown,Nothing)
-- (52,False,Unknown,Nothing)
-- (53,False,Unknown,Nothing)
-- (54,False,Unknown,Nothing)
-- (55,False,Yes,Nothing)
-- (56,False,Unknown,Nothing)
-- (57,False,Yes,Nothing)
-- (58,False,Unknown,Nothing)
-- (59,False,Yes,Nothing)
-- (60,False,Unknown,Nothing)
-- (61,False,Unclear "Yes, if both commissioners are female; otherwise there are more than two commissioners.",Nothing)
-- (62,False,Unclear "No, if both commissioners are female; otherwise there are more than two commissioners.",Nothing)
-- (63,False,Yes,Nothing)
-- (64,False,Unknown,Nothing)
-- (65,False,Unknown,Nothing)
-- (66,False,Yes,Nothing)
-- (67,False,Yes,Nothing)
-- (68,False,Yes,Nothing)
-- (69,False,Yes,Nothing)
-- (70,False,No,Nothing)
-- (71,False,Unknown,Nothing)
-- (72,False,Unknown,Nothing)
-- (73,False,Unknown,Nothing)
-- (74,False,Unknown,Nothing)
-- (75,False,Unknown,Nothing)
-- (76,False,Yes,Nothing)
-- (77,False,Unclear "Yes, if both commissioners are female; otherwise there are more than two commissioners.",Nothing)
-- (78,False,Unclear "No, if both commissioners are female; otherwise there are more than two commissioners.",Nothing)
-- (79,False,Unknown,Nothing)
-- (80,False,Yes,Nothing)
-- (81,False,Yes,Nothing)
-- (82,False,Yes,Nothing)
-- (83,False,Unknown,Nothing)
-- (84,False,Yes,Nothing)
-- (85,False,No,Nothing)
-- (86,False,No,Nothing)
-- (87,False,Unclear "Yes, on one reading",Nothing)
-- (88,False,Unclear "Don't know, on one reading",Nothing)
-- (89,False,Yes,Nothing)
-- (90,False,Yes,Nothing)
-- (91,False,Unknown,Nothing)
-- (92,False,Yes,Nothing)
-- (93,False,Yes,Nothing)
-- (94,False,Unknown,Nothing)
-- (95,False,Unknown,Nothing)
-- (96,False,Yes,Nothing)
-- (97,False,Yes,Nothing)
-- (98,False,Unknown,Nothing)
-- (99,False,Yes,Nothing)
-- (100,False,Yes,Nothing)
-- (101,False,Yes,Nothing)
-- (102,False,Unknown,Nothing)
-- (103,False,Yes,Nothing)
-- (104,False,Unknown,Nothing)
-- (105,False,No,Nothing)
-- (106,False,No,Nothing)
-- (107,False,Yes,Nothing)
-- (108,False,Yes,Nothing)
-- (109,False,Unclear "No, just one",Nothing)
-- (110,False,Yes,Nothing)
-- (111,False,Unclear "Yes, on a collective/cumulative reading of the conclusion.",Nothing)
-- (112,False,Unclear "Yes, on a distributive reading of \"Smith and Jones\".",Nothing)
-- (113,False,Yes,Nothing)
-- (114,True,Yes,Just Yes)
-- (115,True,Yes,Just Yes)
-- (116,True,Yes,Just Yes)
-- (117,True,Yes,Just Yes)
-- (118,True,Yes,Just Yes)
-- (120,True,Yes,Just Yes)
-- (121,True,Yes,Just Yes)
-- (122,True,Yes,Just Yes)
-- (123,True,Yes,Just Yes)
-- (124,False,Yes,Just Unknown)
-- (125,True,Unknown,Just Unknown)
-- (126,False,Yes,Just Unknown)
-- (127,True,Unclear "Yes, on a distributive reading of the question.",Just Unknown)
-- (128,True,Yes,Just Yes)
-- (129,True,Unclear "Yes, on one possible reading",Just Yes)
-- (130,True,Unclear "Don't know, on one possible reading",Just Unknown)
-- (131,True,Yes,Just Yes)
-- (132,True,Yes,Just Yes)
-- (133,True,Yes,Just Yes)
-- (134,True,Yes,Just Yes)
-- (135,True,Yes,Just Yes)
-- (136,True,Unknown,Just Unknown)
-- (137,False,Yes,Nothing)
-- (138,False,Yes,Just Unknown)
-- (139,True,Yes,Just Yes)
-- (140,True,Yes,Just Yes)
-- (141,True,Unknown,Just Unknown)
-- (142,True,Yes,Just Yes)
-- (143,True,Unknown,Just Unknown)
-- (144,True,Yes,Just Yes)
-- (145,True,Yes,Just Yes)
-- (146,True,Yes,Just Yes)
-- (147,True,No,Just No)
-- (148,True,Yes,Just Yes)
-- (149,True,Yes,Just Yes)
-- (150,True,Yes,Just Yes)
-- (151,True,Yes,Just Yes)
-- (152,True,Yes,Just Yes)
-- (153,True,Yes,Just Yes)
-- (154,True,Yes,Just Yes)
-- (155,True,Yes,Just Yes)
-- (156,True,Unknown,Just Unknown)
-- (157,True,Yes,Just Yes)
-- (158,True,Unknown,Just Unknown)
-- (159,True,Yes,Just Yes)
-- (160,True,Unclear "Yes, on one possible reading",Just Yes)
-- (161,True,Unclear "Don't know, on one possible reading",Just Yes)
-- (162,True,Yes,Just Yes)
-- (163,True,No,Just No)
-- (164,True,Yes,Just Yes)
-- (165,True,Yes,Just Yes)
-- (166,True,Yes,Just Yes)
-- (167,True,No,Just No)
-- (168,True,Yes,Just Yes)
-- (169,True,Unclear "Yes, on one possible reading",Just Yes)
-- (170,True,Unclear "Yes, on one possible reading",Just Unknown)
-- (171,False,Yes,Nothing)
-- (172,False,Yes,Nothing)
-- (173,True,Yes,Just Yes)
-- (174,True,Unknown,Just Unknown)
-- (175,True,Unclear "Yes, on one possible reading/parse",Just Yes)
-- (176,True,Unclear "Yes, on one possible reading/parse",Just Yes)
-- (177,True,Unknown,Just Unknown)
-- (178,True,Yes,Just Yes)
-- (179,True,Yes,Just Yes)
-- (180,True,Yes,Just Yes)
-- (181,False,Unknown,Just Yes)
-- (182,True,Unclear "Yes, on one reading",Just Yes)
-- (183,True,Unclear "Yes, on one reading",Just Yes)
-- (184,True,Unknown,Just Unknown)
-- (185,True,Unclear "Yes, on one reading",Just Yes)
-- (186,True,Unclear "Yes, on one reading",Just Yes)
-- (187,True,Unclear "Yes, on one reading",Just Yes)
-- (188,False,Unknown,Just Yes)
-- (189,True,Unclear "Yes, on one reading",Just Yes)
-- (190,True,Unclear "Yes, on one reading",Just Yes)
-- (191,False,Yes,Nothing)
-- (192,False,Unknown,Nothing)
-- (193,False,Yes,Nothing)
-- (194,False,Unknown,Nothing)
-- (195,False,Yes,Nothing)
-- (196,True,Yes,Just Yes)
-- (197,False,Yes,Nothing)
-- (198,False,Unclear "No / don't know",Nothing)
-- (199,False,Unclear "Yes (for a former university student)",Nothing)
-- (200,False,Unknown,Nothing)
-- (201,False,Unknown,Nothing)
-- (202,False,Yes,Nothing)
-- (203,False,Yes,Nothing)
-- (204,False,No,Nothing)
-- (205,False,No,Nothing)
-- (206,False,Unknown,Nothing)
-- (207,False,Unknown,Nothing)
-- (208,False,Yes,Nothing)
-- (209,False,No,Nothing)
-- (210,False,No,Nothing)
-- (211,False,No,Nothing)
-- (212,False,Yes,Nothing)
-- (213,False,Unclear "??: Yes for a mouse; ?? No for an animal",Nothing)
-- (214,False,Yes,Nothing)
-- (215,False,Unknown,Nothing)
-- (216,False,Yes,Nothing)
-- (217,False,Unknown,Nothing)
-- (218,False,Yes,Nothing)
-- (219,False,Unknown,Nothing)
-- (220,False,Yes,Nothing)
-- (221,False,Unknown,Nothing)
-- (222,False,Unknown,Nothing)
-- (223,False,No,Nothing)
-- (224,False,Yes,Nothing)
-- (225,False,Unknown,Nothing)
-- (226,False,Unknown,Nothing)
-- (227,False,No,Nothing)
-- (228,False,Unknown,Nothing)
-- (229,False,No,Nothing)
-- (230,False,Yes,Nothing)
-- (231,False,Unknown,Nothing)
-- (232,False,Yes,Nothing)
-- (233,False,Yes,Nothing)
-- (234,False,Unknown,Nothing)
-- (235,False,Yes,Nothing)
-- (236,False,Yes,Nothing)
-- (237,False,Yes,Nothing)
-- (238,False,Yes,Nothing)
-- (239,False,Yes,Nothing)
-- (240,False,Unknown,Nothing)
-- (241,False,Yes,Nothing)
-- (242,False,Yes,Nothing)
-- (243,False,Yes,Nothing)
-- (244,False,Unclear "Yes, on one reading of the premise",Nothing)
-- (245,False,Unclear "Yes, on one reading of the premise",Nothing)
-- (246,False,Yes,Nothing)
-- (247,False,Unknown,Nothing)
-- (248,False,Yes,Nothing)
-- (249,False,Yes,Nothing)
-- (250,False,Unclear "Yes, on one reading of the premise",Nothing)
-- (251,False,Yes,Nothing)
-- (252,False,Yes,Nothing)
-- (253,False,Unknown,Nothing)
-- (254,False,Unknown,Nothing)
-- (255,False,Yes,Nothing)
-- (256,False,Unclear "Don't know, on one reading of the premise",Nothing)
-- (257,False,Unclear "Yes, on one reading of the premise",Nothing)
-- (258,False,No,Nothing)
-- (259,False,Yes,Nothing)
-- (260,False,Yes,Nothing)
-- (261,False,Yes,Nothing)
-- (262,False,Yes,Nothing)
-- (263,False,Unknown,Nothing)
-- (264,False,Yes,Nothing)
-- (265,False,Yes,Nothing)
-- (266,False,Yes,Nothing)
-- (267,False,Yes,Nothing)
-- (268,False,Yes,Nothing)
-- (269,False,Unknown,Nothing)
-- (270,False,Yes,Nothing)
-- (271,False,Unknown,Nothing)
-- (272,False,Unknown,Nothing)
-- (273,False,Unknown,Nothing)
-- (274,False,Unknown,Nothing)
-- (275,False,Unknown,Nothing)
-- (276,False,Unclear "",Nothing)
-- (277,False,Unknown,Nothing)
-- (278,False,No,Nothing)
-- (279,False,No,Nothing)
-- (280,False,Unknown,Nothing)
-- (281,False,Unknown,Nothing)
-- (282,False,No,Nothing)
-- (283,False,Unknown,Nothing)
-- (284,False,Yes,Nothing)
-- (285,False,Unknown,Nothing)
-- (286,False,No,Nothing)
-- (287,False,Unknown,Nothing)
-- (288,False,Yes,Nothing)
-- (289,False,No,Nothing)
-- (290,False,Yes,Nothing)
-- (291,False,Unclear "?Yes",Nothing)
-- (292,False,Unknown,Nothing)
-- (293,False,Unknown,Nothing)
-- (294,False,Yes,Nothing)
-- (295,False,Unknown,Nothing)
-- (296,False,Unknown,Nothing)
-- (297,False,Yes,Nothing)
-- (298,False,Yes,Nothing)
-- (299,False,No,Nothing)
-- (300,False,Yes,Nothing)
-- (301,False,Yes,Nothing)
-- (302,False,Yes,Nothing)
-- (303,False,Yes,Nothing)
-- (304,False,Unknown,Nothing)
-- (305,False,Unclear "",Nothing)
-- (306,False,Yes,Nothing)
-- (307,False,Yes,Nothing)
-- (308,False,Unclear "Yes on one scoping; unknown on another scoping",Nothing)
-- (309,False,Unclear "",Nothing)
-- (310,False,Unclear "",Nothing)
-- (311,False,Yes,Nothing)
-- (312,False,Yes,Nothing)
-- (313,False,No,Nothing)
-- (314,False,Yes,Nothing)
-- (315,False,Yes,Nothing)
-- (316,False,Yes,Nothing)
-- (317,False,Yes,Nothing)
-- (318,False,No,Nothing)
-- (319,False,Yes,Nothing)
-- (320,False,Yes,Nothing)
-- (321,False,Yes,Nothing)
-- (322,False,Yes,Nothing)
-- (323,False,Yes,Nothing)
-- (324,False,Yes,Nothing)
-- (325,False,Yes,Nothing)
-- (326,False,Yes,Nothing)
-- (327,False,Unknown,Nothing)
-- (328,False,Yes,Nothing)
-- (329,False,Unknown,Nothing)
-- (330,False,Yes,Nothing)
-- (331,False,Yes,Nothing)
-- (332,False,Yes,Nothing)
-- (333,False,Yes,Nothing)
-- (334,False,Yes,Nothing)
-- (335,False,Unknown,Nothing)
-- (336,False,Yes,Nothing)
-- (337,False,Unknown,Nothing)
-- (338,False,Yes,Nothing)
-- (339,False,No,Nothing)
-- (340,False,Unknown,Nothing)
-- (341,False,Unknown,Nothing)
-- (342,False,Yes,Nothing)
-- (343,False,Yes,Nothing)
-- (344,False,Yes,Nothing)
-- (345,False,Yes,Nothing)
-- (346,False,Yes,Nothing)
